# Generated by Django 4.2.4 on 2023-09-05 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import offices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', offices.fields.OrderField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('amenity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='offices.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('amenity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='offices.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('capacity', models.PositiveIntegerField()),
                ('availability', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='offices/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='offices.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
                ('amenity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offices.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('amenity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='offices.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='BidOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_status', models.CharField(choices=[('Selected', 'selected'), ('Waiting', 'waiting'), ('spaces_full', 'Spaces Full')], default='approved', max_length=20)),
                ('office_purpose', models.CharField(choices=[('organization', 'Organization'), ('business', 'Business'), ('school', 'School')], default='business', max_length=250)),
                ('bid', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bid_approval', models.CharField(choices=[('not approved', 'Not Approved'), ('approved', 'Approved'), ('waiting', 'Waiting')], default='approved', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='offices.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-bid',),
            },
        ),
        migrations.AddField(
            model_name='amenities',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='offices.office'),
        ),
    ]
